spring.application.name=springweb

spring.ai.ollama.base-url=https://shiny-space-waddle-v6pjq4r9x5j92pxgg-11434.app.github.dev/
spring.ai.ollama.chat.model=smollm2:135m

server.port=8080
server.address=0.0.0.0